server:
  port: 8080

spring:
  application:
    name: delivery-service

  # DB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      minimum-idle: 20
      maximum-pool-size: 25
      connection-test-query: SELECT 1

  #H2
  h2:
    console:
      path: /h2-console
      enabled: true

  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        auto_quote_keyword: true
        format_sql: true
        highlight_sql: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: embedded

# jwt
security:
  jwt:
    secret: ${JWT_SECRET:nb3OdXITTBLQcZdAJgz5wBq2pmWP2TFwuwJyub8uVzQ=}
    access-ttl-minutes: 30
    refresh-ttl-days: 14

logging:
  level:
    root: info
    org.example.delivery: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace